import logging
import re
from fractions import Fraction

import numpy as np
import scipy
from ase import Atom, Atoms
from ase.io.vasp import read_vasp
from phonopy.physical_units import get_physical_units
from pymatgen.core.operations import SymmOp

from pulgon_tools.detect_generalized_translational_group import (
    CyclicGroupAnalyzer,
)
from pulgon_tools.detect_point_group import LineGroupAnalyzer
from pulgon_tools.line_group_table import get_family_num_from_sym_symbol
from pulgon_tools.utils import (
    brute_force_generate_group_subsequent,
    find_axis_center_of_nanotube,
    get_character_withparities,
    get_matrices_withPhase,
)

DEFAULT_SYMMETRY_TOLERANCE = 1e-2
DEFAULT_LAYER_TOLERANCE = 0.05
DEFAULT_MATRIX_TOLERANCE = 1e-2
DEFAULT_PERMUTATION_TOLERANCE = 1e-3
GENERATOR_ROUND_DECIMALS = 6
GENERATOR_CLASSIFICATION_TOLERANCE = 1e-2
PROJECTOR_RANK_TOLERANCE = 1e-8
PROJECTOR_GAP_WARNING_TOLERANCE = 0.05
DEFAULT_TO_THZ = get_physical_units().DefaultToTHz


def get_adapted_matrix_withparities(
    DictParams,
    num_atom,
    matrices,
    *,
    rank_tolerance=PROJECTOR_RANK_TOLERANCE,
    gap_warning_tolerance=PROJECTOR_GAP_WARNING_TOLERANCE,
):
    """
    Calculate the symmetry projection basis matrix for irreducible representation

    Parameters
    ----------
    DictParams : dict
        Dictionary of parameters:
           {"qpoints": q/k point | float,
            "nrot": The rotational quantum number of the structure "Cn" | int,
            "order": The multiplication order from generators to symmetry operations | list,
            "family": The line group family index | int,
            "a": The period length in z direction | float}
    num_atom : int
        The number of atoms
    matrices : list of numpy arrays
        The matrices used to calculate the symmetry projection basis matrix
    rank_tolerance : float
        Singular-value cutoff used after residualizing duplicate subspaces.
    gap_warning_tolerance : float
        Warning threshold for a small singular-value gap in projectors.

    Returns
    -------
    adapted : numpy array
        The symmetry projection basis matrix for irreducible representation
    dimension : list of int
        The dimensions of the irreducible representations
    """
    (
        representation_mat,
        paras_values,
        paras_symbols,
    ) = get_character_withparities(DictParams)
    ndof = 3 * num_atom

    adapted = []
    dimension = []
    for ii, rep_mat in enumerate(representation_mat):  # loop IR
        if rep_mat.ndim == 1:
            IR_ndim = 1
        else:
            IR_ndim = rep_mat.shape[-1]

        projector = np.zeros((ndof, ndof), dtype=np.complex128)

        for kk in range(len(rep_mat)):
            if rep_mat.ndim == 1:
                chara_conj = rep_mat[kk].conj()
            else:
                chara_conj = rep_mat[kk].trace().conj()
            projector += chara_conj * matrices[kk]
        projector = IR_ndim * projector / len(rep_mat)

        num_modes = projector.trace().real

        if np.isclose(num_modes, np.round(num_modes)):
            num_modes = np.round(num_modes).astype(np.int32)
        else:
            print("num_modes=", num_modes)
            logging.ERROR("num_modes is not an integer")
        if num_modes == 0:
            continue
        u, s, vh = scipy.linalg.svd(projector)
        basis = u[:, :num_modes]
        residualized = False
        if adapted:
            # Low-order line groups can make distinct table rows project onto
            # the same subspace; keep only the new independent directions.
            existing = np.concatenate(adapted, axis=1)
            basis = basis - existing @ (existing.conj().T @ basis)
            u_res, s_res, _ = scipy.linalg.svd(basis, full_matrices=False)
            num_modes = np.count_nonzero(s_res > rank_tolerance)
            if num_modes == 0:
                continue
            basis = u_res[:, :num_modes]
            residualized = True
        if residualized:
            error = 0
        elif num_modes < ndof:
            error = 1 - np.abs(s[num_modes - 1] - s[num_modes]) / np.abs(
                s[num_modes - 1]
            )
        else:
            error = 0

        if error > gap_warning_tolerance:
            print("ii=", ii, "error=", error)

        dimension.append(basis.shape[1])
        adapted.append(basis)
    adapted = np.concatenate(adapted, axis=1)
    if adapted.shape[0] != adapted.shape[1] or adapted.shape[0] != ndof:
        print("adapted.shape=", adapted.shape)
    return adapted, dimension, paras_values, paras_symbols


def _compute_unreduced_z_translations(generators, order_ops):
    """Compute unreduced fractional z-translations for each group element.

    When the group is generated by brute_force_generate_group_subsequent,
    the z-component of translations is reduced mod 1 (via np.remainder).
    This loses information needed for correct Bloch phase factors at
    non-zero q-points. This function recomputes the true (unreduced)
    fractional z-translation by composing the generators without
    modular reduction.

    Parameters
    ----------
    generators : ndarray, shape (n_gen, 4, 4)
        Generator affine matrices.
    order_ops : list of list of int
        Generator index sequences for each group element.
        Index 0 = identity, indices 1..n_gen = generators (1-indexed).

    Returns
    -------
    list of float
        Unreduced fractional z-translation for each group element.
    """
    gen_Rzz = [g[2, 2] for g in generators]
    gen_tz = [g[2, 3] for g in generators]

    result = []
    for seq in order_ops:
        tz = 0.0
        for idx in seq:
            if idx == 0:
                continue
            g = idx - 1
            tz = gen_tz[g] + gen_Rzz[g] * tz
        result.append(tz)
    return result


def _extract_generator_angles(
    mats, matrix_tolerance=GENERATOR_CLASSIFICATION_TOLERANCE
):
    """Extract geometric angles from C2' and sigma_d generators.

    For each generator in mats, detect C2' (det=+1, R[2,2]=-1) and
    sigma_d (det=-1, R[2,2]=+1) and extract their orientation angles
    in the xy-plane.

    Returns dict with keys 'alphaU' (C2' angle) and 'betaS' (sigma_d angle).
    """
    angles = {}
    for mat in mats:
        R = mat[:3, :3]
        det = np.linalg.det(R)
        if np.isclose(R[2, 2], -1, atol=matrix_tolerance) and det > 0:
            # C2' perpendicular rotation
            angles["alphaU"] = np.arctan2(R[0, 1], R[0, 0]) / 2
        elif np.isclose(R[2, 2], 1, atol=matrix_tolerance) and det < 0:
            # sigma_d mirror plane
            angles["betaS"] = np.arctan2(R[0, 1], R[0, 0]) / 2
    return angles


def _extract_translation_parameters(trans_sym, a_lattice):
    """Extract translation parameters needed by the irrep tables.

    Pure translations are represented as the Q=1 screw limit so family-1
    tables can use the same code path for ``T`` and ``T_Q`` groups.
    """
    if trans_sym == "T":
        return {"Q_screw": 1.0, "Q_num": 1, "f_screw": float(a_lattice)}

    match = re.match(r"\(C([^|]+)\|T\d+\(([^)]+)\)\)", trans_sym)
    if match is None:
        return {}

    q_frac = Fraction(match.group(1))
    return {
        "Q_screw": float(q_frac),
        "Q_num": q_frac.numerator,
        "f_screw": float(match.group(2)),
    }


def _select_cyclic_candidate(cyclic, rota_sym):
    """Return the first cyclic candidate that maps to a known family."""
    cyclic_groups, _ = cyclic.get_cyclic_group()
    for index, trans_sym in enumerate(cyclic_groups):
        family = get_family_num_from_sym_symbol(trans_sym, rota_sym)
        if family is not None:
            return index, trans_sym, family
    raise ValueError(
        f"Cannot identify a line-group family for axial point group {rota_sym} "
        f"and cyclic groups {cyclic_groups}."
    )


def _get_cyclic_generator(cyclic, index, trans_sym):
    """Return the generator matrix for the selected cyclic candidate."""
    if trans_sym == "T":
        return np.eye(4)

    sym_operations = cyclic._sym_operations[index]
    if isinstance(sym_operations, list):
        op = sym_operations[1]
    else:
        op = sym_operations

    fractional_translation = (
        op.translation_vector @ np.linalg.inv(cyclic._atom.cell)
    ) % 1
    return SymmOp.from_rotation_and_translation(
        rotation_matrix=op.rotation_matrix,
        translation_vec=[0, 0, fractional_translation[2]],
    ).affine_matrix


def _s2n_affine_generator(nrot):
    """Return the axial S2n generator for family-2 line groups.

    ``LineGroupAnalyzer.get_generators()`` currently returns the proper
    rotation subgroup generator for axial ``S2n`` groups, e.g. ``C2`` for
    ``S4``. Family 2 irreps are tabulated against the improper generator
    ``sigma_h C_{2n}``, so the dataset must use that generator explicitly.
    """
    angle = np.pi / nrot
    generator = np.eye(4)
    generator[:3, :3] = np.array(
        [
            [np.cos(angle), -np.sin(angle), 0],
            [np.sin(angle), np.cos(angle), 0],
            [0, 0, -1],
        ]
    )
    return generator


def _normalize_generators_for_irrep_table(
    family,
    nrot,
    trans_op,
    rots_op,
):
    """Return generators aligned with the irrep-table column order.

    The detected generators are minimal geometric generators.  In low-order
    cases, a standard table generator can collapse to identity and be omitted,
    shifting all later generator indices in ``order_ops``.  Keep explicit
    placeholders only for the affected families so generic cases are unchanged.
    """
    if family == 2:
        # Family 2 is tabulated against S2n = sigma_h C_{2n}; the point-group
        # detector may return the proper rotation subgroup instead.
        rots_op = np.array(
            [
                np.round(
                    _s2n_affine_generator(nrot),
                    GENERATOR_ROUND_DECIMALS,
                )
            ]
        )
    elif family == 8 and nrot == 1:
        # Family 8 table columns are [screw, Cn, sigmaV].  When n=1, Cn is
        # identity but its column must remain so sigmaV keeps index 3.
        rots = np.asarray(rots_op)
        if rots.size != 0:
            rots_op = np.concatenate(([np.eye(4)], rots), axis=0)

    rots_op = np.asarray(rots_op)
    if rots_op.size != 0:
        return np.vstack(([trans_op], rots_op))
    return np.asarray([trans_op])


def get_linegroup_symmetry_dataset(
    poscar,
    tolerance=DEFAULT_SYMMETRY_TOLERANCE,
    layer_tolerance=DEFAULT_LAYER_TOLERANCE,
    matrix_tolerance=DEFAULT_MATRIX_TOLERANCE,
):
    """Extract line-group symmetry data for projector construction.

    Args:
        poscar: path to a POSCAR file, ASE Atom, or ASE Atoms object.
        tolerance: distance tolerance for symmetry detection.
        layer_tolerance: fractional z-layer tolerance for cyclic-group
            monomer translation candidates.
        matrix_tolerance: tolerance for matrix classification and group
            closure during operation generation.
    """
    if type(poscar) == str:
        atom = read_vasp(poscar)
    elif type(poscar) == Atom or type(poscar) == Atoms:
        atom = poscar
    else:
        print("Unknown input")

    cyclic = CyclicGroupAnalyzer(
        atom,
        tolerance=tolerance,
        layer_tolerance=layer_tolerance,
    )
    atom_center = find_axis_center_of_nanotube(cyclic._primitive)

    obj = LineGroupAnalyzer(
        atom_center,
        tolerance=tolerance,
        matrix_tolerance=matrix_tolerance,
    )

    rota_sym = obj.sch_symbol
    selected_cyclic, trans_sym, family = _select_cyclic_candidate(
        cyclic, rota_sym
    )
    nrot = obj.get_rotational_symmetry_number()
    aL = atom_center.cell[2, 2]

    trans_op = np.round(
        _get_cyclic_generator(cyclic, selected_cyclic, trans_sym),
        GENERATOR_ROUND_DECIMALS,
    )
    rots_op = np.round(obj.get_generators(), GENERATOR_ROUND_DECIMALS)
    mats = _normalize_generators_for_irrep_table(
        family, nrot, trans_op, rots_op
    )
    ops, order_ops = brute_force_generate_group_subsequent(
        mats, symprec=matrix_tolerance
    )

    gen_angles = _extract_generator_angles(
        mats, matrix_tolerance=matrix_tolerance
    )
    gen_angles.update(_extract_translation_parameters(trans_sym, aL))

    unreduced_tz = _compute_unreduced_z_translations(mats, order_ops)

    ops_car_sym = []
    for idx, op in enumerate(ops):
        cart_trans = op[:3, 3].copy() * aL
        cart_trans[2] = unreduced_tz[idx] * aL
        tmp_sym = SymmOp.from_rotation_and_translation(op[:3, :3], cart_trans)
        ops_car_sym.append(tmp_sym)
    return atom_center, family, nrot, aL, ops_car_sym, order_ops, gen_angles


def get_adapted_eigenmodes(D, adapted, dimensions):
    """
    Calculate the frequencies and eigenvectors at a given qpoint
    using the symmetry-adapted basis.

    Parameters
    ----------
    D : array_like
        The dynamical matrix at the given qpoint.
    adapted : numpy array
        The symmetry projection basis matrix for irreducible representation.
    dimensions : list of int
        The dimensions of the irreducible representations.

    Returns
    -------
    freq : numpy array
        The frequencies at the given qpoint.
    eigenvecs : numpy array
        The eigenvectors at the given qpoint.
    """

    D = adapted.conj().T @ D @ adapted
    start = 0
    tmp_eigvec, tmp_eigval, freqs = [], [], []
    for ir in range(len(dimensions)):
        end = start + dimensions[ir]
        block = D[start:end, start:end]
        eigval, eigvecs = np.linalg.eigh(block)
        tmp_vec = adapted[:, start:end] @ eigvecs
        tmp_eigvec.append(tmp_vec)
        tmp_eigval.append(eigval)
        start = end
    eigvals = np.concatenate(tmp_eigval)
    eigenvecs = np.concatenate(tmp_eigvec, axis=1)
    freqs = np.sqrt(np.abs(eigvals)) * np.sign(eigvals) * DEFAULT_TO_THZ
    return freqs, eigvals, eigenvecs


def get_eigenmodes_from_phonon(
    phonon,
    q_vector,
    adapted=True,
    *,
    tolerance=DEFAULT_SYMMETRY_TOLERANCE,
    layer_tolerance=DEFAULT_LAYER_TOLERANCE,
    matrix_tolerance=DEFAULT_MATRIX_TOLERANCE,
    permutation_tolerance=DEFAULT_PERMUTATION_TOLERANCE,
):
    if adapted:
        num_atom = len(phonon.primitive.get_atomic_numbers())
        atom = Atoms(
            cell=phonon.primitive.cell,
            numbers=phonon.primitive.numbers,
            positions=phonon.primitive.positions,
        )
        (
            atom_center,
            family,
            nrot,
            aL,
            ops_car_sym,
            order_ops,
            gen_angles,
        ) = get_linegroup_symmetry_dataset(
            atom,
            tolerance=tolerance,
            layer_tolerance=layer_tolerance,
            matrix_tolerance=matrix_tolerance,
        )

        qp_1dim = np.array(q_vector[2]) * 2 * np.pi
        qp_1dim = qp_1dim / aL
        DictParams = {
            "qpoints": qp_1dim,
            "nrot": nrot,
            "order": order_ops,
            "family": family,
            "a": aL,
            **gen_angles,
        }

        matrices = get_matrices_withPhase(
            atom_center,
            ops_car_sym,
            qp_1dim,
            symprec=permutation_tolerance,
        )

        (
            adapted,
            dimensions,
            paras_values,
            paras_symbols,
        ) = get_adapted_matrix_withparities(DictParams, num_atom, matrices)
        dmat = phonon.get_dynamical_matrix_at_q(q_vector)

        freqs, eigvals, eigvecs = get_adapted_eigenmodes(
            dmat, adapted, dimensions
        )
        return freqs, eigvals, eigvecs, dimensions, paras_values, paras_symbols
    else:
        dmat = phonon.get_dynamical_matrix_at_q(q_vector)
        eigvals, eigvecs = np.linalg.eigh(dmat)
        freqs = np.sqrt(np.abs(eigvals)) * np.sign(eigvals) * DEFAULT_TO_THZ
        return freqs, eigvals, eigvecs
